name: 02 CI Workflow

on:
  push:
    paths:
      - "app/**"
      - "tests/**"
      - ".github/workflows/02-ci.yml"
  workflow_dispatch:

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-versions: ${{ steps.set-v.outputs.versions }}
    steps:
      - id: set-v
        run: echo "versions=${{ secrets.PYTHON_VERSIONS }}" >> "$GITHUB_OUTPUT"

  run-tests:
    needs: setup-matrix 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.setup-matrix.outputs.matrix-versions) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: python -m unittest discover -s tests -v

      - name: Show Python version
        run: python --version