# 1. بنعرف الـ ARG في أول السطر
ARG BASE_IMAGE=python:3.12-slim

# 2. بنستخدم الـ ARG في الـ FROM
FROM ${BASE_IMAGE}

WORKDIR /app

# بننسخ مجلد الـ app
COPY app ./app

EXPOSE 8000

# تشغيل التطبيق
CMD ["python", "app/app.py"]